// <auto-generated />
using System;
using App.Modules.KWMODULENAME.Infrastructure.Persistence.EF.DbContexts.Implementations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.Modules.KWMODULENAME.Infrastructure.Migrations
{
    [DbContext(typeof(ModuleDbContext))]
    partial class ModuleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("kwmodulename")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("App.Modules.KWMODULENAME.Domain.Domains.Examples.Structures.AtRest.Entities.Implementations.ExampleA", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0)
                        .HasComment("Gets or sets the identifier.");

                    b.Property<string>("CreatedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(5)
                        .HasComment("Gets or sets the principal id who created the record.");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(4)
                        .HasComment("Gets or sets the UTC DateTime created on.");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnOrder(11)
                        .HasComment("The textual Description.");

                    b.Property<Guid>("ExampleTypeFK")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(13)
                        .HasComment("Gets or sets the foreign key. Classifies this entity by a reference-data type. Since it is navigable, the property name suffix is an 'FK', not 'Id'");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnOrder(12)
                        .HasComment("Gets or sets whether this entity is active.");

                    b.Property<string>("LastModifiedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(7)
                        .HasComment("Gets or sets the principal id who last modified the record.");

                    b.Property<DateTimeOffset>("LastModifiedOnUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(6)
                        .HasComment("Gets or sets the UTC DateTime when the record was last modified.");

                    b.Property<int>("RecordMutability")
                        .HasColumnType("int")
                        .HasColumnOrder(2)
                        .HasComment("Who/what can mutate/change the record.");

                    b.Property<int>("RecordState")
                        .HasColumnType("int")
                        .HasColumnOrder(3)
                        .HasComment("The state of the Record in terms of persistence.");

                    b.Property<string>("StateChangedByPrincipalId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(9)
                        .HasComment("Gets or sets the principal id who changed the state (nullable).");

                    b.Property<DateTimeOffset?>("StateChangedOnDateTimeUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(8)
                        .HasComment("Gets or sets the date when record state changed (nullable for soft delete).");

                    b.Property<DateTime>("SysEndTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("SysEndTime")
                        .HasComment("Stores the Sys End Time value for the Example A record.");

                    b.Property<DateTime>("SysStartTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("SysStartTime")
                        .HasComment("Stores the Sys Start Time value for the Example A record.");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnOrder(1)
                        .HasComment("Gets or sets the datastore concurrency check timestamp.");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnOrder(10)
                        .HasComment("The (display) title.");

                    b.HasKey("Id");

                    b.HasIndex("ExampleTypeFK")
                        .HasDatabaseName("IX_ExampleA_ExampleTypeFK");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("IX_ExampleAs_Id");

                    b.HasIndex("RecordState")
                        .HasDatabaseName("IX_ExampleAs_RecordState");

                    b.ToTable("ExampleAs", "kwmodulename_examples", t =>
                        {
                            t.HasComment("Example entity A - demonstrates a domain entity inheriting from with title, description, active flag, and a foreign key to reference data. Replace with your actual domain entity when cloning.");
                        });

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("ExampleAsHistory", "kwmodulename_examples");
                                ttb
                                    .HasPeriodStart("SysStartTime")
                                    .HasColumnName("SysStartTime");
                                ttb
                                    .HasPeriodEnd("SysEndTime")
                                    .HasColumnName("SysEndTime");
                            }));
                });

            modelBuilder.Entity("App.Modules.KWMODULENAME.Domain.Domains.Examples.Structures.AtRest.Entities.Implementations.ExampleAExampleB", b =>
                {
                    b.Property<Guid>("ExampleAFK")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Gets or sets the foreign key. Since it is navigable, the property name suffix is an 'FK', not 'Id'");

                    b.Property<Guid>("ExampleBFK")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Gets or sets the foreign key. Since it is navigable, the property name suffix is an 'FK', not 'Id'");

                    b.Property<string>("CreatedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(4)
                        .HasComment("Gets or sets the principal id who created the record.");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(3)
                        .HasComment("Gets or sets the UTC DateTime created on.");

                    b.Property<string>("LastModifiedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(6)
                        .HasComment("Gets or sets the principal id who last modified the record.");

                    b.Property<DateTimeOffset>("LastModifiedOnUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(5)
                        .HasComment("Gets or sets the UTC DateTime when the record was last modified.");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnOrder(9)
                        .HasComment("Optional payload: notes or context about this association.");

                    b.Property<int>("RecordMutability")
                        .HasColumnType("int")
                        .HasColumnOrder(1)
                        .HasComment("Who/what can mutate/change the record.");

                    b.Property<int>("RecordState")
                        .HasColumnType("int")
                        .HasColumnOrder(2)
                        .HasComment("The state of the Record in terms of persistence.");

                    b.Property<string>("StateChangedByPrincipalId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(8)
                        .HasComment("Gets or sets the principal id who changed the state (nullable).");

                    b.Property<DateTimeOffset?>("StateChangedOnDateTimeUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(7)
                        .HasComment("Gets or sets the date when record state changed (nullable for soft delete).");

                    b.Property<DateTime>("SysEndTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("SysEndTime")
                        .HasComment("Stores the Sys End Time value for the Example A Example B record.");

                    b.Property<DateTime>("SysStartTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("SysStartTime")
                        .HasComment("Stores the Sys Start Time value for the Example A Example B record.");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnOrder(0)
                        .HasComment("Gets or sets the datastore concurrency check timestamp.");

                    b.HasKey("ExampleAFK", "ExampleBFK");

                    b.HasIndex("ExampleAFK")
                        .HasDatabaseName("IX_ExampleAExampleB_ExampleAFK");

                    b.HasIndex("ExampleBFK")
                        .HasDatabaseName("IX_ExampleAExampleB_ExampleBFK");

                    b.HasIndex("RecordState")
                        .HasDatabaseName("IX_ExampleAExampleBs_RecordState");

                    b.ToTable("ExampleAExampleBs", "kwmodulename_examples", t =>
                        {
                            t.HasComment("Explicit join entity linking and in a many-to-many relationship.");
                        });

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("ExampleAExampleBsHistory", "kwmodulename_examples");
                                ttb
                                    .HasPeriodStart("SysStartTime")
                                    .HasColumnName("SysStartTime");
                                ttb
                                    .HasPeriodEnd("SysEndTime")
                                    .HasColumnName("SysEndTime");
                            }));
                });

            modelBuilder.Entity("App.Modules.KWMODULENAME.Domain.Domains.Examples.Structures.AtRest.Entities.Implementations.ExampleB", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0)
                        .HasComment("Gets or sets the identifier.");

                    b.Property<string>("CreatedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(5)
                        .HasComment("Gets or sets the principal id who created the record.");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(4)
                        .HasComment("Gets or sets the UTC DateTime created on.");

                    b.Property<Guid>("ExampleAId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(10)
                        .HasComment("Opaque identifier for the related Example A aggregate.");

                    b.Property<string>("LastModifiedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(7)
                        .HasComment("Gets or sets the principal id who last modified the record.");

                    b.Property<DateTimeOffset>("LastModifiedOnUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(6)
                        .HasComment("Gets or sets the UTC DateTime when the record was last modified.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnOrder(11)
                        .HasComment("The name of the model.");

                    b.Property<int>("RecordMutability")
                        .HasColumnType("int")
                        .HasColumnOrder(2)
                        .HasComment("Who/what can mutate/change the record.");

                    b.Property<int>("RecordState")
                        .HasColumnType("int")
                        .HasColumnOrder(3)
                        .HasComment("The state of the Record in terms of persistence.");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnOrder(12)
                        .HasComment("Gets or sets the sort order.");

                    b.Property<string>("StateChangedByPrincipalId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(9)
                        .HasComment("Gets or sets the principal id who changed the state (nullable).");

                    b.Property<DateTimeOffset?>("StateChangedOnDateTimeUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(8)
                        .HasComment("Gets or sets the date when record state changed (nullable for soft delete).");

                    b.Property<DateTime>("SysEndTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("SysEndTime")
                        .HasComment("Stores the Sys End Time value for the Example B record.");

                    b.Property<DateTime>("SysStartTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("SysStartTime")
                        .HasComment("Stores the Sys Start Time value for the Example B record.");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnOrder(1)
                        .HasComment("Gets or sets the datastore concurrency check timestamp.");

                    b.HasKey("Id");

                    b.HasIndex("ExampleAId")
                        .HasDatabaseName("IX_ExampleBs_ExampleAId");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("IX_ExampleBs_Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_ExampleB_Name");

                    b.HasIndex("RecordState")
                        .HasDatabaseName("IX_ExampleBs_RecordState");

                    b.ToTable("ExampleBs", "kwmodulename_examples", t =>
                        {
                            t.HasComment("Example entity B - demonstrates a child/related domain entity that references via a foreign key. Inherits from for standard identity, audit, and record-state plumbing. Replace with your actual domain entity when cloning.");
                        });

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("ExampleBsHistory", "kwmodulename_examples");
                                ttb
                                    .HasPeriodStart("SysStartTime")
                                    .HasColumnName("SysStartTime");
                                ttb
                                    .HasPeriodEnd("SysEndTime")
                                    .HasColumnName("SysEndTime");
                            }));
                });

            modelBuilder.Entity("App.Modules.KWMODULENAME.Domain.Domains.Examples.Structures.AtRest.Entities.Implementations.ExampleType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0)
                        .HasComment("Gets or sets the identifier.");

                    b.Property<string>("CreatedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(5)
                        .HasComment("Gets or sets the principal id who created the record.");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(4)
                        .HasComment("Gets or sets the UTC DateTime created on.");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnOrder(13)
                        .HasComment("The textual Description.");

                    b.Property<int>("DisplayOrderHint")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnOrder(18)
                        .HasComment("A Hint to the Interface (UI/API) to organise item order on initial display. Non-unique. May be overridden by MRU settings.");

                    b.Property<string>("DisplayStyleHint")
                        .HasMaxLength(64)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnOrder(17)
                        .HasComment("A Hint on how to display the item. Consider using the field for a Classname that will mean something to the UX interface.");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(11)
                        .HasComment("Get/Set whether the entity is enabled or not.");

                    b.Property<int?>("EnumValue")
                        .HasColumnType("int")
                        .HasColumnOrder(22)
                        .HasComment("The integer value from the original . null for custom entries added beyond the built-in enum values.");

                    b.Property<DateTimeOffset?>("FromUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(20)
                        .HasComment("Gets or sets the start datetime.");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnOrder(10)
                        .HasComment("Get/Set the list item's unique key.");

                    b.Property<string>("LastModifiedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(7)
                        .HasComment("Gets or sets the principal id who last modified the record.");

                    b.Property<DateTimeOffset>("LastModifiedOnUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(6)
                        .HasComment("Gets or sets the UTC DateTime when the record was last modified.");

                    b.Property<Guid?>("MediaContentFK")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(16)
                        .HasComment("FK to MediaContent when MediaReferenceKind is Media. Null otherwise.");

                    b.Property<string>("MediaFontKey")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnOrder(15)
                        .HasComment("Font/icon key media source. Should be set only when MediaReferenceKind is Font.");

                    b.Property<int>("MediaReferenceKind")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnOrder(14)
                        .HasComment("Discriminator that declares which media source field is active (None, Font, Media).");

                    b.Property<int>("RecordMutability")
                        .HasColumnType("int")
                        .HasColumnOrder(2)
                        .HasComment("Who/what can mutate/change the record.");

                    b.Property<int>("RecordState")
                        .HasColumnType("int")
                        .HasColumnOrder(3)
                        .HasComment("The state of the Record in terms of persistence.");

                    b.Property<string>("StateChangedByPrincipalId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(9)
                        .HasComment("Gets or sets the principal id who changed the state (nullable).");

                    b.Property<DateTimeOffset?>("StateChangedOnDateTimeUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(8)
                        .HasComment("Gets or sets the date when record state changed (nullable for soft delete).");

                    b.Property<DateTime>("SysEndTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("SysEndTime")
                        .HasComment("Stores the Sys End Time value for the Example Type record.");

                    b.Property<DateTime>("SysStartTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("SysStartTime")
                        .HasComment("Stores the Sys Start Time value for the Example Type record.");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnOrder(1)
                        .HasComment("Gets or sets the datastore concurrency check timestamp.");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnOrder(12)
                        .HasComment("The (display) title.");

                    b.Property<DateTimeOffset?>("ToUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(21)
                        .HasComment("Gets or sets the end datetime.");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnOrder(19)
                        .HasComment("Stores the Value value for the Example Type record.");

                    b.HasKey("Id");

                    b.HasIndex("Enabled")
                        .HasDatabaseName("IX_ExampleType_Enabled");

                    b.HasIndex("EnumValue")
                        .IsUnique()
                        .HasDatabaseName("IX_ExampleTypes_EnumValue")
                        .HasFilter("[EnumValue] IS NOT NULL");

                    b.HasIndex("FromUtc")
                        .HasDatabaseName("IX_ExampleType_FromUtc");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("IX_ExampleTypes_Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("IX_ExampleType_Key");

                    b.HasIndex("MediaContentFK")
                        .HasDatabaseName("IX_ExampleType_MediaContentFK");

                    b.HasIndex("RecordState")
                        .HasDatabaseName("IX_ExampleTypes_RecordState");

                    b.HasIndex("ToUtc")
                        .HasDatabaseName("IX_ExampleType_ToUtc");

                    b.ToTable("ExampleTypes", "kwmodulename_ref", t =>
                        {
                            t.HasComment("Reference data entity that classifies instances. Many-to-one: each has one .");
                        });

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("ExampleTypesHistory", "kwmodulename_ref");
                                ttb
                                    .HasPeriodStart("SysStartTime")
                                    .HasColumnName("SysStartTime");
                                ttb
                                    .HasPeriodEnd("SysEndTime")
                                    .HasColumnName("SysEndTime");
                            }));

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedByPrincipalId = "SYSTEM",
                            CreatedOnUtc = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Example type: Undefined.",
                            DisplayOrderHint = 0,
                            Enabled = false,
                            EnumValue = 0,
                            Key = "Undefined",
                            LastModifiedByPrincipalId = "SYSTEM",
                            LastModifiedOnUtc = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            MediaReferenceKind = 0,
                            RecordMutability = 4,
                            RecordState = 4,
                            Title = "Undefined",
                            Value = "Undefined"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedByPrincipalId = "SYSTEM",
                            CreatedOnUtc = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Example type: NotApplicable.",
                            DisplayOrderHint = 1,
                            Enabled = true,
                            EnumValue = 1,
                            Key = "NotApplicable",
                            LastModifiedByPrincipalId = "SYSTEM",
                            LastModifiedOnUtc = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            MediaReferenceKind = 0,
                            RecordMutability = 4,
                            RecordState = 4,
                            Title = "NotApplicable",
                            Value = "NotApplicable"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedByPrincipalId = "SYSTEM",
                            CreatedOnUtc = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Example type: Unspecified.",
                            DisplayOrderHint = 2,
                            Enabled = false,
                            EnumValue = 2,
                            Key = "Unspecified",
                            LastModifiedByPrincipalId = "SYSTEM",
                            LastModifiedOnUtc = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            MediaReferenceKind = 0,
                            RecordMutability = 4,
                            RecordState = 4,
                            Title = "Unspecified",
                            Value = "Unspecified"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedByPrincipalId = "SYSTEM",
                            CreatedOnUtc = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Example type: Unknown.",
                            DisplayOrderHint = 3,
                            Enabled = false,
                            EnumValue = 3,
                            Key = "Unknown",
                            LastModifiedByPrincipalId = "SYSTEM",
                            LastModifiedOnUtc = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            MediaReferenceKind = 0,
                            RecordMutability = 4,
                            RecordState = 4,
                            Title = "Unknown",
                            Value = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CreatedByPrincipalId = "SYSTEM",
                            CreatedOnUtc = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Example type: General.",
                            DisplayOrderHint = 4,
                            Enabled = true,
                            EnumValue = 4,
                            Key = "General",
                            LastModifiedByPrincipalId = "SYSTEM",
                            LastModifiedOnUtc = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            MediaReferenceKind = 0,
                            RecordMutability = 4,
                            RecordState = 4,
                            Title = "General",
                            Value = "General"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CreatedByPrincipalId = "SYSTEM",
                            CreatedOnUtc = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Example type: Specialised.",
                            DisplayOrderHint = 5,
                            Enabled = true,
                            EnumValue = 5,
                            Key = "Specialised",
                            LastModifiedByPrincipalId = "SYSTEM",
                            LastModifiedOnUtc = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            MediaReferenceKind = 0,
                            RecordMutability = 4,
                            RecordState = 4,
                            Title = "Specialised",
                            Value = "Specialised"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            CreatedByPrincipalId = "SYSTEM",
                            CreatedOnUtc = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Example type: Advanced.",
                            DisplayOrderHint = 6,
                            Enabled = true,
                            EnumValue = 6,
                            Key = "Advanced",
                            LastModifiedByPrincipalId = "SYSTEM",
                            LastModifiedOnUtc = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            MediaReferenceKind = 0,
                            RecordMutability = 4,
                            RecordState = 4,
                            Title = "Advanced",
                            Value = "Advanced"
                        });
                });

            modelBuilder.Entity("App.Modules.KWMODULENAME.Domain.Domains.Examples.Structures.AtRest.Entities.Implementations.ExampleValueObject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0)
                        .HasComment("Gets or sets the identifier.");

                    b.Property<string>("CreatedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(5)
                        .HasComment("Gets or sets the principal id who created the record.");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(4)
                        .HasComment("Gets or sets the UTC DateTime created on.");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnOrder(11)
                        .HasComment("The textual Description.");

                    b.Property<Guid>("ExampleAFK")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Gets or sets the parent foreign key. Since it is navigable, the property name suffix is an 'FK', not 'Id'.");

                    b.Property<string>("LastModifiedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(7)
                        .HasComment("Gets or sets the principal id who last modified the record.");

                    b.Property<DateTimeOffset>("LastModifiedOnUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(6)
                        .HasComment("Gets or sets the UTC DateTime when the record was last modified.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnOrder(10)
                        .HasComment("The name of the model.");

                    b.Property<int>("RecordMutability")
                        .HasColumnType("int")
                        .HasColumnOrder(2)
                        .HasComment("Who/what can mutate/change the record.");

                    b.Property<int>("RecordState")
                        .HasColumnType("int")
                        .HasColumnOrder(3)
                        .HasComment("The state of the Record in terms of persistence.");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnOrder(12)
                        .HasComment("Gets or sets the sort order hint for display purposes.");

                    b.Property<string>("StateChangedByPrincipalId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(9)
                        .HasComment("Gets or sets the principal id who changed the state (nullable).");

                    b.Property<DateTimeOffset?>("StateChangedOnDateTimeUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(8)
                        .HasComment("Gets or sets the date when record state changed (nullable for soft delete).");

                    b.Property<DateTime>("SysEndTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("SysEndTime")
                        .HasComment("Stores the Sys End Time value for the Example Value Object record.");

                    b.Property<DateTime>("SysStartTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("SysStartTime")
                        .HasComment("Stores the Sys Start Time value for the Example Value Object record.");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnOrder(1)
                        .HasComment("Gets or sets the datastore concurrency check timestamp.");

                    b.HasKey("Id");

                    b.HasIndex("ExampleAFK");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("IX_ExampleValueObjects_Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_ExampleValueObject_Name");

                    b.HasIndex("RecordState")
                        .HasDatabaseName("IX_ExampleValueObjects_RecordState");

                    b.ToTable("ExampleValueObjects", "kwmodulename_examples", t =>
                        {
                            t.HasComment("A value-object–style child of . One-to-many: each owns zero or more of these.");
                        });

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("ExampleValueObjectsHistory", "kwmodulename_examples");
                                ttb
                                    .HasPeriodStart("SysStartTime")
                                    .HasColumnName("SysStartTime");
                                ttb
                                    .HasPeriodEnd("SysEndTime")
                                    .HasColumnName("SysEndTime");
                            }));
                });

            modelBuilder.Entity("App.Modules.Sys.Shared.Domains.Infrastructure.Models.Implementations.MediaContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key for the Media Content record.");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("The blob path for the default (culture-neutral) content, including the container prefix (e.g. \"media-signed/agreements/agreements/{guid}.md\").");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("SHA-256 hash of the default content at import/publish time.");

                    b.Property<string>("ContentHashAlgorithm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("The hash algorithm used (e.g. \"SHA-256\").");

                    b.Property<long?>("ContentSizeBytes")
                        .HasColumnType("bigint")
                        .HasComment("Size of the blob content in bytes. Used to populate Content-Length headers for downloads, display file-size hints in the UI, and support accessible media descriptions. Null until the blob has been written and its size confirmed.");

                    b.Property<string>("CreatedByPrincipalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Gets or sets the principal id who created the record.");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("Gets or sets the UTC DateTime created on. Changed To DateTimeOffset.");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("The textual Description. Note that it records put Descriptions in DBs makes it harder to be international later. Consider using the field for a token that a post processor could recognise and replace with a localised text resource.");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Get/Set the list item's unique key. Note: Consider the difference with .");

                    b.Property<string>("LastModifiedByPrincipalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Gets or sets the principal id who last modified the record.");

                    b.Property<DateTimeOffset>("LastModifiedOnUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("Gets or sets the UTC DateTime when the record was last modified.");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("MIME type of the content. (e.g. \"text/markdown\", \"text/plain\", \"image/png\").");

                    b.Property<int>("RecordMutability")
                        .HasColumnType("int")
                        .HasComment("gets or sets who can mutate a record. Default should be Custom (end users).");

                    b.Property<int>("RecordState")
                        .HasColumnType("int")
                        .HasComment("The state of the Record in terms of persistence.");

                    b.Property<string>("StateChangedByPrincipalId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Gets or sets the principal id who changed the state (nullable).");

                    b.Property<DateTimeOffset?>("StateChangedOnDateTimeUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("Gets or sets the date when record state changed (nullable for soft delete). Null until a state transition (soft delete, archive, etc.) occurs.");

                    b.Property<DateTime>("SysEndTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("SysEndTime")
                        .HasComment("Stores the Sys End Time value for the Media Content record.");

                    b.Property<DateTime>("SysStartTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("SysStartTime")
                        .HasComment("Stores the Sys Start Time value for the Media Content record.");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasComment("Gets or sets the datastore concurrency check timestamp. Note that this is filled in when persisted in the db -- so it's usable to determine whether Record is New or not.");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("The (display) title");

                    b.HasKey("Id");

                    b.ToTable("MediaContents", "sys_core", t =>
                        {
                            t.ExcludeFromMigrations();

                            t.HasComment("Concrete entity for culture-neutral media content. See for full documentation.");
                        });

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("MediaContentsHistory", "sys_core");
                                ttb
                                    .HasPeriodStart("SysStartTime")
                                    .HasColumnName("SysStartTime");
                                ttb
                                    .HasPeriodEnd("SysEndTime")
                                    .HasColumnName("SysEndTime");
                            }));
                });

            modelBuilder.Entity("App.Modules.KWMODULENAME.Domain.Domains.Examples.Structures.AtRest.Entities.Implementations.ExampleA", b =>
                {
                    b.HasOne("App.Modules.KWMODULENAME.Domain.Domains.Examples.Structures.AtRest.Entities.Implementations.ExampleType", "ExampleType")
                        .WithMany()
                        .HasForeignKey("ExampleTypeFK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExampleType");
                });

            modelBuilder.Entity("App.Modules.KWMODULENAME.Domain.Domains.Examples.Structures.AtRest.Entities.Implementations.ExampleAExampleB", b =>
                {
                    b.HasOne("App.Modules.KWMODULENAME.Domain.Domains.Examples.Structures.AtRest.Entities.Implementations.ExampleA", "ExampleA")
                        .WithMany()
                        .HasForeignKey("ExampleAFK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("App.Modules.KWMODULENAME.Domain.Domains.Examples.Structures.AtRest.Entities.Implementations.ExampleB", "ExampleB")
                        .WithMany()
                        .HasForeignKey("ExampleBFK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExampleA");

                    b.Navigation("ExampleB");
                });

            modelBuilder.Entity("App.Modules.KWMODULENAME.Domain.Domains.Examples.Structures.AtRest.Entities.Implementations.ExampleType", b =>
                {
                    b.HasOne("App.Modules.Sys.Shared.Domains.Infrastructure.Models.Implementations.MediaContent", "MediaContent")
                        .WithMany()
                        .HasForeignKey("MediaContentFK")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MediaContent");
                });

            modelBuilder.Entity("App.Modules.KWMODULENAME.Domain.Domains.Examples.Structures.AtRest.Entities.Implementations.ExampleValueObject", b =>
                {
                    b.HasOne("App.Modules.KWMODULENAME.Domain.Domains.Examples.Structures.AtRest.Entities.Implementations.ExampleA", "ExampleA")
                        .WithMany("ValueObjects")
                        .HasForeignKey("ExampleAFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExampleA");
                });

            modelBuilder.Entity("App.Modules.Sys.Shared.Domains.Infrastructure.Models.Implementations.MediaContent", b =>
                {
                    b.OwnsOne("App.Modules.Sys.Substrate.Domains.Measurements.Models.MediaDimensions", "IntrinsicDimensions", b1 =>
                        {
                            b1.Property<Guid>("MediaContentId")
                                .HasColumnType("uniqueidentifier")
                                .HasComment("Primary key for the Media Content record.");

                            b1.Property<decimal>("Height")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("IntrinsicHeight")
                                .HasColumnOrder(1)
                                .HasComment("Intrinsic height in .");

                            b1.Property<DateTime>("SysEndTime")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("datetime2")
                                .HasColumnName("SysEndTime")
                                .HasComment("Stores the Sys End Time value for the Media Content record.");

                            b1.Property<DateTime>("SysStartTime")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("datetime2")
                                .HasColumnName("SysStartTime")
                                .HasComment("Stores the Sys Start Time value for the Media Content record.");

                            b1.Property<int>("Unit")
                                .HasColumnType("int")
                                .HasColumnName("IntrinsicDimensionUnit")
                                .HasColumnOrder(2)
                                .HasComment("Unit shared by both axes.");

                            b1.Property<decimal>("Width")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("IntrinsicWidth")
                                .HasColumnOrder(0)
                                .HasComment("Intrinsic width in .");

                            b1.HasKey("MediaContentId");

                            b1.ToTable("MediaContents", "sys_core", t =>
                                {
                                    t.HasComment("Concrete entity for culture-neutral media content. See for full documentation.");
                                });

                            b1.ToTable(tb => tb.IsTemporal(ttb =>
                                    {
                                        ttb.UseHistoryTable("MediaContentsHistory", "sys_core");
                                        ttb
                                            .HasPeriodStart("SysStartTime")
                                            .HasColumnName("SysStartTime");
                                        ttb
                                            .HasPeriodEnd("SysEndTime")
                                            .HasColumnName("SysEndTime");
                                    }));

                            b1.WithOwner()
                                .HasForeignKey("MediaContentId");
                        });

                    b.Navigation("IntrinsicDimensions");
                });

            modelBuilder.Entity("App.Modules.KWMODULENAME.Domain.Domains.Examples.Structures.AtRest.Entities.Implementations.ExampleA", b =>
                {
                    b.Navigation("ValueObjects");
                });
#pragma warning restore 612, 618
        }
    }
}
